version: '3'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - WAIT_HOSTS=db:5432,user-db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  db:
    image: postgres:14.0
    environment:
      - POSTGRES_DB=celebration_board
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  user-db:
    image: postgres:14.0
    environment: 
      - POSTGRES_DB=celebration_user_board
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password